<?php
function pos_api_expose_menu() {
	//Post Format: {request : {uname, pass}}
	//Secure later by changing access arguments to something more role based
	$routers['pos-api/auth'] = array(
		'title' => 'Authenticate POS Users',
		'page callback' => 'pos_api_expose_auth',
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK,
		'file' => 'includes/auth.route.inc'
  	);

  	$routers['pos-api/clock'] = array(
  		'title' => 'Clock RPC',
  		'description' => 'Clock in or clock out callback for POS Users.',
		'page callback' => 'pos_api_expose_clock',
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK,
		'file' => 'includes/clock.route.inc'
  	);

  	$routers['pos-api/clockState'] = array(
  		'title' => 'Clock State RPC',
  		'description' => 'Query clock state for initial button states on app.',
		'page callback' => 'pos_api_expose_clockState',
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK,
		'file' => 'includes/clock.route.inc'
  	);

  	$routers['pos-api/products/%/%'] = array(
  		'title' => 'Search Products',
  		'description' => 'Search for products by name or sku.',
		'page callback' => 'pos_api_expose_product_search',
		'access arguments' => array('access content'),
		'page arguments' => array(2, 3),
		'type' => MENU_CALLBACK,
		'file' => 'includes/products.route.inc'
  	);

	return $routers;
}

function pos_api_expose_respond($response, $die = FALSE) {
	drupal_set_header('Content-Type: application/json');
	print json_encode($response);

	if($die) {
		die();
	}
}
function last_event($uid, $event_type) {
	return db_fetch_object(db_query("SELECT eid, checkin, checkout FROM {pos_api_expose_timesheet} WHERE uid = '%d' AND event_type = '%s' ORDER BY checkin DESC", $uid, $event_type));
}