<?php
function pos_api_expose_menu() {
	//Post Format: {request : {uname, pass}}
	//Secure later by changing access arguments to something more role based
	$routers['pos-api/auth'] = array(
		'title' => 'Authenticate POS Users',
		'page callback' => 'pos_api_expose_auth',
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK,
		'file' => 'includes/auth.route.inc'
  	);

  	$routers['pos-api/clock'] = array(
  		'title' => 'Clock RPC',
  		'description' => 'Clock in or clock out callback for POS Users.',
		'page callback' => 'pos_api_expose_clock',
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK,
		'file' => 'includes/clock.route.inc'
  	);

  	$routers['pos-api/clockState'] = array(
  		'title' => 'Clock State RPC',
  		'description' => 'Query clock state for initial button states on app.',
		'page callback' => 'pos_api_expose_clockState',
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK,
		'file' => 'includes/clock.route.inc'
  	);

  	$routers['pos-api/product-scan'] = array(
  		'title' => 'Scan Product Barcode',
  		'description' => 'Search for products by a barcode.',
		'page callback' => 'pos_api_expose_product_scan',
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK,
		'file' => 'includes/products.route.inc'
  	);

  	$routers['pos-api/ticket-statuses'] = array(
  		'title' => 'Ticket Statuses.',
  		'description' => 'Get a list of ticket status.',
		'page callback' => 'pos_api_expose_ticket_statuses',
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK,
		'file' => 'includes/tickets.route.inc'
  	);

  	$routers['pos-api/new-ticket'] = array(
  		'title' => 'New Ticket',
  		'description' => 'Create a new ticket and get ticketId.',
		'page callback' => 'pos_api_expose_new_ticket',
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK,
		'file' => 'includes/tickets.route.inc'
  	);

  	$routers['pos-api/ticket/update-customer'] = array(
  		'title' => 'Update Ticket Customer',
  		'description' => 'Update customer on a ticket.',
		'page callback' => 'pos_api_expose_ticket_update_customer',
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK,
		'file' => 'includes/tickets.route.inc'
  	);

  	$routers['pos-api/ticket/add-product'] = array(
  		'title' => 'Add Product to Ticket',
  		'description' => 'Add a product to ticket.',
		'page callback' => 'pos_api_expose_ticket_add_product',
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK,
		'file' => 'includes/tickets.route.inc'
  	);

  	$routers['pos-api/tickets/%/%'] = array(
  		'title' => 'Search Tickets',
  		'description' => 'Search for tickets by ticket id or customer info.',
		'page callback' => 'pos_api_expose_ticket_search',
		'access arguments' => array('access content'),
		'page arguments' => array(2, 3),
		'type' => MENU_CALLBACK,
		'file' => 'includes/tickets.route.inc'
  	);

  	$routers['pos-api/products/%/%'] = array(
  		'title' => 'Search Products',
  		'description' => 'Search for products by name or sku.',
		'page callback' => 'pos_api_expose_product_search',
		'access arguments' => array('access content'),
		'page arguments' => array(2, 3),
		'type' => MENU_CALLBACK,
		'file' => 'includes/products.route.inc'
  	);

  	$routers['pos-api/customers/%/%'] = array(
  		'title' => 'Search Customers',
  		'description' => 'Search for customer by company name, number, address or other field keywords.',
		'page callback' => 'pos_api_expose_customer_search',
		'access arguments' => array('access content'),
		'page arguments' => array(2, 3),
		'type' => MENU_CALLBACK,
		'file' => 'includes/customers.route.inc'
  	);

  	$routers['pos-api/customer'] = array(
  		'title' => 'Search Customers',
  		'description' => 'Search for customer by customer uid, number, address or other field keywords.',
		'page callback' => 'pos_api_expose_get_customer',
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK,
		'file' => 'includes/customers.route.inc'
  	);

	return $routers;
}

function pos_api_expose_respond($response, $die = FALSE) {
	drupal_set_header('Content-Type: application/json');
	print json_encode($response);

	if($die) {
		die();
	}
}
function _pos_api_expose_last_event($uid, $event_type) {
	return db_fetch_object(db_query("SELECT eid, checkin, checkout FROM {pos_api_expose_timesheet} WHERE uid = '%d' AND event_type = '%s' ORDER BY checkin DESC", $uid, $event_type));
}

function _pos_api_expose_uid_from_token($token) {
	return db_result(db_query("SELECT paet.uid FROM {pos_api_expose_tokens} paet WHERE paet.token = '%s'", $token));
}