<?php
function pos_api_expose_menu() {
	//Post Format: {request : {uname, pass}}
	//Secure later by changing access arguments to something more role based
	$routers['pos-api/auth'] = array(
		'title' => 'Authenticate POS Users',
		'page callback' => 'pos_api_expose_auth',
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK,
		'file' => 'includes/auth.route.inc'
  	);

  	$routers['pos-api/clock'] = array(
  		'title' => 'Clock RPC',
  		'description' => 'Clock in or clock out callback for POS Users.',
		'page callback' => 'pos_api_expose_clock',
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK,
		'file' => 'includes/clock.route.inc'
  	);

  	$routers['pos-api/clockState'] = array(
  		'title' => 'Clock State RPC',
  		'description' => 'Query clock state for initial button states on app.',
		'page callback' => 'pos_api_expose_clockState',
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK,
		'file' => 'includes/clock.route.inc'
  	);

  	$routers['pos-api/product-scan'] = array(
  		'title' => 'Scan Product Barcode',
  		'description' => 'Search for products by a barcode.',
		'page callback' => 'pos_api_expose_product_scan',
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK,
		'file' => 'includes/products.route.inc'
  	);

  	$routers['pos-api/ticket-statuses'] = array(
  		'title' => 'Ticket Statuses.',
  		'description' => 'Get a list of ticket status.',
		'page callback' => 'pos_api_expose_ticket_statuses',
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK,
		'file' => 'includes/tickets.route.inc'
  	);

  	$routers['pos-api/new-ticket'] = array(
  		'title' => 'New Ticket',
  		'description' => 'Create a new ticket and get ticketId.',
		'page callback' => 'pos_api_expose_new_ticket',
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK,
		'file' => 'includes/tickets.route.inc'
  	);

  	$routers['pos-api/load-ticket'] = array(
  		'title' => 'Load Ticket Products',
  		'description' => 'Load products from an existing ticketId.',
		'page callback' => 'pos_api_expose_load_ticket_products',
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK,
		'file' => 'includes/products.route.inc'
  	);

  	$routers['pos-api/ticket/update-customer'] = array(
  		'title' => 'Update Ticket Customer',
  		'description' => 'Update customer on a ticket.',
		'page callback' => 'pos_api_expose_ticket_update_customer',
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK,
		'file' => 'includes/tickets.route.inc'
  	);

  	$routers['pos-api/ticket/update-qty'] = array(
  		'title' => 'Update Ticket Qty',
  		'description' => 'Update customer on a qty.',
		'page callback' => 'pos_api_expose_ticket_update_product_qty',
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK,
		'file' => 'includes/tickets.route.inc'
  	);

  	$routers['pos-api/ticket/get-current'] = array(
  		'title' => 'Update Ticket Customer',
  		'description' => 'Get current ticket to patch dirty caches on typeaheadjs.',
		'page callback' => 'pos_api_expose_ticket_current',
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK,
		'file' => 'includes/tickets.route.inc'
  	);

  	$routers['pos-api/ticket/add-product'] = array(
  		'title' => 'Add Product to Ticket',
  		'description' => 'Add a product to ticket.',
		'page callback' => 'pos_api_expose_ticket_add_product',
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK,
		'file' => 'includes/tickets.route.inc'
  	);

  	$routers['pos-api/ticket/remove-product'] = array(
  		'title' => 'Remove Product from Ticket',
  		'description' => 'Remove a product from ticket.',
		'page callback' => 'pos_api_expose_ticket_remove_product',
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK,
		'file' => 'includes/tickets.route.inc'
  	);

  	$routers['pos-api/ticket/update-total'] = array(
  		'title' => 'Update Ticket Totals',
  		'description' => 'Update a ticket totals.',
		'page callback' => 'pos_api_expose_ticket_update_totals',
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK,
		'file' => 'includes/tickets.route.inc'
  	);

  	$routers['pos-api/ticket/update-status'] = array(
  		'title' => 'Update Ticket Status',
  		'description' => 'Update a ticket status.',
		'page callback' => 'pos_api_expose_ticket_update_status',
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK,
		'file' => 'includes/tickets.route.inc'
  	);

  	$routers['pos-api/ticket/delivery'] = array(
  		'title' => 'Ticket Delivey',
  		'description' => 'Update ticket delivery.',
  		'page callback' => 'pos_api_expose_ticket_update_zone',
  		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK,
		'file' => 'includes/tickets.route.inc'
  	);

  	$routers['pos-api/ticket/delivery'] = array(
  		'title' => 'Ticket Delivey',
  		'description' => 'Update ticket delivery.',
  		'page callback' => 'pos_api_expose_ticket_update_zone',
  		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK,
		'file' => 'includes/tickets.route.inc'
  	);

  	$routers['pos-api/ticket/cash-checkout'] = array(
  		'title' => 'Cash Checkout',
  		'description' => 'Checkout with cash.',
  		'page callback' => 'pos_api_expose_ticket_cash_checkout',
  		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK,
		'file' => 'includes/tickets.route.inc'
  	);

  	$routers['pos-api/tickets/%/%'] = array(
  		'title' => 'Search Tickets',
  		'description' => 'Search for tickets by ticket id or customer info.',
		'page callback' => 'pos_api_expose_ticket_search',
		'access arguments' => array('access content'),
		'page arguments' => array(2, 3),
		'type' => MENU_CALLBACK,
		'file' => 'includes/tickets.route.inc'
  	);

  	$routers['pos-api/products/%/%'] = array(
  		'title' => 'Search Products',
  		'description' => 'Search for products by name or sku.',
		'page callback' => 'pos_api_expose_product_search',
		'access arguments' => array('access content'),
		'page arguments' => array(2, 3),
		'type' => MENU_CALLBACK,
		'file' => 'includes/products.route.inc'
  	);

  	$routers['pos-api/customers/%/%'] = array(
  		'title' => 'Search Customers',
  		'description' => 'Search for customer by company name, number, address or other field keywords.',
		'page callback' => 'pos_api_expose_customer_search',
		'access arguments' => array('access content'),
		'page arguments' => array(2, 3),
		'type' => MENU_CALLBACK,
		'file' => 'includes/customers.route.inc'
  	);

  	$routers['pos-api/customer'] = array(
  		'title' => 'Search Customers',
  		'description' => 'Search for customer by customer uid, number, address or other field keywords.',
		'page callback' => 'pos_api_expose_get_customer',
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK,
		'file' => 'includes/customers.route.inc'
  	);

  	$routers['pos-api/customer/info'] = array(
  		'title' => 'Customer Info',
  		'description' => 'Get customer info.',
		'page callback' => 'pos_api_expose_customer_info',
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK,
		'file' => 'includes/customers.route.inc'
  	);

  	$routers['pos-api/customer/invoice'] = array(
  		'title' => 'Customer Invoices',
  		'description' => 'Get AHAH customer invoice list.',
		'page callback' => 'pos_api_expose_customer_invoices',
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK,
		'file' => 'includes/customers.route.inc'
  	);

  	$routers['pos-api/employee/recent-tickets'] = array(
  		'title' => 'Get Recent Tickets',
  		'description' => 'Get AHAH recent ticket list.',
		'page callback' => 'pos_api_expose_recent_invoices',
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK,
		'file' => 'includes/tickets.route.inc'
  	);

  	$routers['pos-api/ticket/quote'] = array(
  		'title' => 'Get List of Quote Tickets',
  		'description' => 'Get AHAH quote ticket list.',
		'page callback' => 'pos_api_expose_quote_invoices',
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK,
		'file' => 'includes/tickets.route.inc'
  	);

  	$routers['pos-api/ticket/open'] = array(
  		'title' => 'Get List of Open Tickets',
  		'description' => 'Get AHAH quote ticket list.',
		'page callback' => 'pos_api_expose_open_invoices',
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK,
		'file' => 'includes/tickets.route.inc'
  	);

  	$routers['pos-api/ticket/closed'] = array(
  		'title' => 'Get List of closed Tickets',
  		'description' => 'Get AHAH closed ticket list.',
		'page callback' => 'pos_api_expose_closed_invoices',
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK,
		'file' => 'includes/tickets.route.inc'
  	);

  	$routers['pos-api/ticket/rma'] = array(
  		'title' => 'RMA Process RPC Handler',
  		'description' => 'Get confirmation of return when object is scanned.',
  		'page callback' => 'pos_api_rma_process',
  		'access arguments' => array('access content'),
  		'type' => MENU_CALLBACK,
  		'file' => 'includes/products.route.inc'
  	);

	return $routers;
}

function pos_api_expose_respond($response, $die = FALSE) {
	drupal_set_header('Content-Type: application/json');
	print json_encode($response);

	if($die) {
		die();
	}
}

function _pos_api_expose_last_event($uid, $event_type) {
	return db_fetch_object(db_query("SELECT eid, checkin, checkout FROM {pos_api_expose_timesheet} WHERE uid = '%d' AND event_type = '%s' ORDER BY checkin DESC", $uid, $event_type));
}

function _pos_api_expose_uid_from_token($token) {
	return db_result(db_query("SELECT paet.uid FROM {pos_api_expose_tokens} paet WHERE paet.token = '%s'", $token));
}

function _pos_api_expose_log_ticket_load($uid, $ticketId) {
	$sql = "INSERT INTO {pos_api_expose_ticket_log} (uid, ticket_id, timestamp) VALUES ('%d', '%d', '%d')";
	db_query($sql, $uid, $ticketId, time());
}